# Generated by Django 3.1.1 on 2020-09-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200910_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(max_length=24),
        ),
    ]
