# Generated by Django 3.1.1 on 2020-09-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200910_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='owner',
        ),
    ]
